<?php


require_once(PLACESTER_PLUGIN_DIR . 'libnew/attributes.php');


class PLX_Legacy_Attributes extends PLX_Placester_Attributes {
	protected $provider_attributes;

	protected function _define_attributes() {
		$attributes = parent::_define_attributes();

		$attributes = array_merge($attributes, $this->provider_attributes = array(
			// Provider
			'mls_id' =>           array(   'name' => 'mls_id',           'type' => self::TEXT_ID,        'group' => 'Provider',               'display' => 'MLS ID'                      ),

			'aid' =>              array(   'name' => 'aid',              'type' => self::TEXT_ID,        'group' => 'Provider',               'display' => 'Agent ID'                    ),
			'aname' =>            array(   'name' => 'aname',            'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Agent Name'                  ),
			'aphone' =>           array(   'name' => 'aphone',           'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Agent Phone'                 ),
			'aemail' =>           array(   'name' => 'aemail',           'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Agent EMail'                 ),
			'alicense' =>         array(   'name' => 'alicense',         'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Agent License'               ),

			'oid' =>              array(   'name' => 'oid',              'type' => self::TEXT_ID,        'group' => 'Provider',               'display' => 'Office ID'                   ),
			'oname' =>            array(   'name' => 'oname',            'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Office Name'                 ),
			'ophone' =>           array(   'name' => 'ophone',           'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Office Phone'                ),
			'oemail' =>           array(   'name' => 'oemail',           'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Office EMail'                ),

			// Co-attribution
			'acoid' =>            array(   'name' => 'acoid',            'type' => self::TEXT_ID,        'group' => 'Provider',               'display' => 'Co-agent ID'                 ),
			'aconame' =>          array(   'name' => 'aconame',          'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-agent Name'               ),
			'acophone' =>         array(   'name' => 'acophone',         'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-agent Phone'              ),
			'acoemail' =>         array(   'name' => 'acoemail',         'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-agent EMail'              ),
			'acolicense' =>       array(   'name' => 'acolicense',       'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-agent License'            ),

			'ocoid' =>            array(   'name' => 'ocoid',            'type' => self::TEXT_ID,        'group' => 'Provider',               'display' => 'Co-office ID'                ),
			'oconame' =>          array(   'name' => 'oconame',          'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-office Name'              ),
			'ocophone' =>         array(   'name' => 'ocophone',         'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-office Phone'             ),
			'ocoemail' =>         array(   'name' => 'ocoemail',         'type' => self::SHORT_TEXT,     'group' => 'Provider',               'display' => 'Co-office EMail'             ),
		));

		$attributes['country']['fixed'] = true;
		$attributes['country']['values'] = array(
			"AD" =>             "Andorra (AD)",
			"AE" =>             "United Arab Emirates (AE)",
			"AF" =>             "Afghanistan (AF)",
			"AG" =>             "Antigua and Barbuda (AG)",
			"AI" =>             "Anguilla (AI)",
			"AL" =>             "Albania (AL)",
			"AM" =>             "Armenia (AM)",
			"AO" =>             "Angola (AO)",
			"AQ" =>             "Antarctica (AQ)",
			"AR" =>             "Argentina (AR)",
			"AS" =>             "Samoa (American) (AS)",
			"AT" =>             "Austria (AT)",
			"AU" =>             "Australia (AU)",
			"AW" =>             "Aruba (AW)",
			"AX" =>             "Aaland Islands (AX)",
			"AZ" =>             "Azerbaijan (AZ)",
			"BA" =>             "Bosnia and Herzegovina (BA)",
			"BB" =>             "Barbados (BB)",
			"BD" =>             "Bangladesh (BD)",
			"BE" =>             "Belgium (BE)",
			"BF" =>             "Burkina Faso (BF)",
			"BG" =>             "Bulgaria (BG)",
			"BH" =>             "Bahrain (BH)",
			"BI" =>             "Burundi (BI)",
			"BJ" =>             "Benin (BJ)",
			"BL" =>             "St Barthelemy (BL)",
			"BM" =>             "Bermuda (BM)",
			"BN" =>             "Brunei (BN)",
			"BO" =>             "Bolivia (BO)",
			"BQ" =>             "Bonaire Sint Eustatius and Saba (BQ)",
			"BR" =>             "Brazil (BR)",
			"BS" =>             "Bahamas (BS)",
			"BT" =>             "Bhutan (BT)",
			"BV" =>             "Bouvet Island (BV)",
			"BW" =>             "Botswana (BW)",
			"BY" =>             "Belarus (BY)",
			"BZ" =>             "Belize (BZ)",
			"CA" =>             "Canada (CA)",
			"CC" =>             "Cocos (Keeling) Islands (CC)",
			"CD" =>             "Congo (Dem. Rep.) (CD)",
			"CF" =>             "Central African Rep. (CF)",
			"CG" =>             "Congo (Rep.) (CG)",
			"CH" =>             "Switzerland (CH)",
			"CI" =>             "Cote d'Ivoire (CI)",
			"CK" =>             "Cook Islands (CK)",
			"CL" =>             "Chile (CL)",
			"CM" =>             "Cameroon (CM)",
			"CN" =>             "China (CN)",
			"CO" =>             "Colombia (CO)",
			"CR" =>             "Costa Rica (CR)",
			"CU" =>             "Cuba (CU)",
			"CV" =>             "Cape Verde (CV)",
			"CW" =>             "Curacao (CW)",
			"CX" =>             "Christmas Island (CX)",
			"CY" =>             "Cyprus (CY)",
			"CZ" =>             "Czech Republic (CZ)",
			"DE" =>             "Germany (DE)",
			"DJ" =>             "Djibouti (DJ)",
			"DK" =>             "Denmark (DK)",
			"DM" =>             "Dominica (DM)",
			"DO" =>             "Dominican Republic (DO)",
			"DZ" =>             "Algeria (DZ)",
			"EC" =>             "Ecuador (EC)",
			"EE" =>             "Estonia (EE)",
			"EG" =>             "Egypt (EG)",
			"EH" =>             "Western Sahara (EH)",
			"ER" =>             "Eritrea (ER)",
			"ES" =>             "Spain (ES)",
			"ET" =>             "Ethiopia (ET)",
			"FI" =>             "Finland (FI)",
			"FJ" =>             "Fiji (FJ)",
			"FK" =>             "Falkland Islands (FK)",
			"FM" =>             "Micronesia (FM)",
			"FO" =>             "Faroe Islands (FO)",
			"FR" =>             "France (FR)",
			"GA" =>             "Gabon (GA)",
			"GB" =>             "Britain (UK) (GB)",
			"GD" =>             "Grenada (GD)",
			"GE" =>             "Georgia (GE)",
			"GF" =>             "French Guiana (GF)",
			"GG" =>             "Guernsey (GG)",
			"GH" =>             "Ghana (GH)",
			"GI" =>             "Gibraltar (GI)",
			"GL" =>             "Greenland (GL)",
			"GM" =>             "Gambia (GM)",
			"GN" =>             "Guinea (GN)",
			"GP" =>             "Guadeloupe (GP)",
			"GQ" =>             "Equatorial Guinea (GQ)",
			"GR" =>             "Greece (GR)",
			"GS" =>             "South Georgia and the South Sandwich Islands (GS)",
			"GT" =>             "Guatemala (GT)",
			"GU" =>             "Guam (GU)",
			"GW" =>             "Guinea-Bissau (GW)",
			"GY" =>             "Guyana (GY)",
			"HK" =>             "Hong Kong (HK)",
			"HM" =>             "Heard Island and McDonald Islands (HM)",
			"HN" =>             "Honduras (HN)",
			"HR" =>             "Croatia (HR)",
			"HT" =>             "Haiti (HT)",
			"HU" =>             "Hungary (HU)",
			"ID" =>             "Indonesia (ID)",
			"IE" =>             "Ireland (IE)",
			"IL" =>             "Israel (IL)",
			"IM" =>             "Isle of Man (IM)",
			"IN" =>             "India (IN)",
			"IO" =>             "British Indian Ocean Territory (IO)",
			"IQ" =>             "Iraq (IQ)",
			"IR" =>             "Iran (IR)",
			"IS" =>             "Iceland (IS)",
			"IT" =>             "Italy (IT)",
			"JE" =>             "Jersey (JE)",
			"JM" =>             "Jamaica (JM)",
			"JO" =>             "Jordan (JO)",
			"JP" =>             "Japan (JP)",
			"KE" =>             "Kenya (KE)",
			"KG" =>             "Kyrgyzstan (KG)",
			"KH" =>             "Cambodia (KH)",
			"KI" =>             "Kiribati (KI)",
			"KM" =>             "Comoros (KM)",
			"KN" =>             "St Kitts and Nevis (KN)",
			"KP" =>             "Korea (North) (KP)",
			"KR" =>             "Korea (South) (KR)",
			"KW" =>             "Kuwait (KW)",
			"KY" =>             "Cayman Islands (KY)",
			"KZ" =>             "Kazakhstan (KZ)",
			"LA" =>             "Laos (LA)",
			"LB" =>             "Lebanon (LB)",
			"LC" =>             "St Lucia (LC)",
			"LI" =>             "Liechtenstein (LI)",
			"LK" =>             "Sri Lanka (LK)",
			"LR" =>             "Liberia (LR)",
			"LS" =>             "Lesotho (LS)",
			"LT" =>             "Lithuania (LT)",
			"LU" =>             "Luxembourg (LU)",
			"LV" =>             "Latvia (LV)",
			"LY" =>             "Libya (LY)",
			"MA" =>             "Morocco (MA)",
			"MC" =>             "Monaco (MC)",
			"MD" =>             "Moldova (MD)",
			"ME" =>             "Montenegro (ME)",
			"MF" =>             "St Martin (French part) (MF)",
			"MG" =>             "Madagascar (MG)",
			"MH" =>             "Marshall Islands (MH)",
			"MK" =>             "Macedonia (MK)",
			"ML" =>             "Mali (ML)",
			"MM" =>             "Myanmar (Burma) (MM)",
			"MN" =>             "Mongolia (MN)",
			"MO" =>             "Macau (MO)",
			"MP" =>             "Northern Mariana Islands (MP)",
			"MQ" =>             "Martinique (MQ)",
			"MR" =>             "Mauritania (MR)",
			"MS" =>             "Montserrat (MS)",
			"MT" =>             "Malta (MT)",
			"MU" =>             "Mauritius (MU)",
			"MV" =>             "Maldives (MV)",
			"MW" =>             "Malawi (MW)",
			"MX" =>             "Mexico (MX)",
			"MY" =>             "Malaysia (MY)",
			"MZ" =>             "Mozambique (MZ)",
			"NA" =>             "Namibia (NA)",
			"NC" =>             "New Caledonia (NC)",
			"NE" =>             "Niger (NE)",
			"NF" =>             "Norfolk Island (NF)",
			"NG" =>             "Nigeria (NG)",
			"NI" =>             "Nicaragua (NI)",
			"NL" =>             "Netherlands (NL)",
			"NO" =>             "Norway (NO)",
			"NP" =>             "Nepal (NP)",
			"NR" =>             "Nauru (NR)",
			"NU" =>             "Niue (NU)",
			"NZ" =>             "New Zealand (NZ)",
			"OM" =>             "Oman (OM)",
			"PA" =>             "Panama (PA)",
			"PE" =>             "Peru (PE)",
			"PF" =>             "French Polynesia (PF)",
			"PG" =>             "Papua New Guinea (PG)",
			"PH" =>             "Philippines (PH)",
			"PK" =>             "Pakistan (PK)",
			"PL" =>             "Poland (PL)",
			"PM" =>             "St Pierre and Miquelon (PM)",
			"PN" =>             "Pitcairn (PN)",
			"PR" =>             "Puerto Rico (PR)",
			"PS" =>             "Palestine (PS)",
			"PT" =>             "Portugal (PT)",
			"PW" =>             "Palau (PW)",
			"PY" =>             "Paraguay (PY)",
			"QA" =>             "Qatar (QA)",
			"RE" =>             "Reunion (RE)",
			"RO" =>             "Romania (RO)",
			"RS" =>             "Serbia (RS)",
			"RU" =>             "Russia (RU)",
			"RW" =>             "Rwanda (RW)",
			"SA" =>             "Saudi Arabia (SA)",
			"SB" =>             "Solomon Islands (SB)",
			"SC" =>             "Seychelles (SC)",
			"SD" =>             "Sudan (SD)",
			"SE" =>             "Sweden (SE)",
			"SG" =>             "Singapore (SG)",
			"SH" =>             "St Helena (SH)",
			"SI" =>             "Slovenia (SI)",
			"SJ" =>             "Svalbard and Jan Mayen (SJ)",
			"SK" =>             "Slovakia (SK)",
			"SL" =>             "Sierra Leone (SL)",
			"SM" =>             "San Marino (SM)",
			"SN" =>             "Senegal (SN)",
			"SO" =>             "Somalia (SO)",
			"SR" =>             "Suriname (SR)",
			"SS" =>             "South Sudan (SS)",
			"ST" =>             "Sao Tome and Principe (ST)",
			"SV" =>             "El Salvador (SV)",
			"SX" =>             "Sint Maarten (SX)",
			"SY" =>             "Syria (SY)",
			"SZ" =>             "Swaziland (SZ)",
			"TC" =>             "Turks and Caicos Is (TC)",
			"TD" =>             "Chad (TD)",
			"TF" =>             "French Southern and Antarctic Lands (TF)",
			"TG" =>             "Togo (TG)",
			"TH" =>             "Thailand (TH)",
			"TJ" =>             "Tajikistan (TJ)",
			"TK" =>             "Tokelau (TK)",
			"TL" =>             "East Timor (TL)",
			"TM" =>             "Turkmenistan (TM)",
			"TN" =>             "Tunisia (TN)",
			"TO" =>             "Tonga (TO)",
			"TR" =>             "Turkey (TR)",
			"TT" =>             "Trinidad and Tobago (TT)",
			"TV" =>             "Tuvalu (TV)",
			"TW" =>             "Taiwan (TW)",
			"TZ" =>             "Tanzania (TZ)",
			"UA" =>             "Ukraine (UA)",
			"UG" =>             "Uganda (UG)",
			"UM" =>             "US minor outlying islands (UM)",
			"US" =>             "United States (US)",
			"UY" =>             "Uruguay (UY)",
			"UZ" =>             "Uzbekistan (UZ)",
			"VA" =>             "Vatican City (VA)",
			"VC" =>             "St Vincent (VC)",
			"VE" =>             "Venezuela (VE)",
			"VG" =>             "Virgin Islands (UK) (VG)",
			"VI" =>             "Virgin Islands (US) (VI)",
			"VN" =>             "Vietnam (VN)",
			"VU" =>             "Vanuatu (VU)",
			"WF" =>             "Wallis and Futuna (WF)",
			"WS" =>             "Samoa (western) (WS)",
			"YE" =>             "Yemen (YE)",
			"YT" =>             "Mayotte (YT)",
			"ZA" =>             "South Africa (ZA)",
			"ZM" =>             "Zambia (ZM)",
			"ZW" =>             "Zimbabwe (ZW)"
		);

		return $attributes;
	}
}


class PLX_Legacy_Parameters extends PLX_Parameters {
	protected function _define_parameters() {
		$parameters = parent::_define_parameters();

		unset($parameters['aname']);
		unset($parameters['aphone']);
		unset($parameters['alicense']);
		unset($parameters['oname']);
		unset($parameters['ophone']);
		unset($parameters['aconame']);
		unset($parameters['acophone']);
		unset($parameters['acolicense']);
		unset($parameters['oconame']);
		unset($parameters['ocophone']);

		$parameters = array_merge(array(
			'include_disabled' => array(   'name' => 'include_disabled',  'type' => PLX_Attributes::BOOLEAN,        'group' => 'Listing',                'display' => 'Disabled Listings'           ),
			'non_import' =>       array(   'name' => 'non_import',        'type' => PLX_Attributes::BOOLEAN,        'group' => 'Listing',                'display' => 'Private Listings'            ),
			'agency_only' =>      array(   'name' => 'agency_only',       'type' => PLX_Attributes::BOOLEAN,        'group' => 'Listing',                'display' => 'Agency Listings'             )
		), $parameters);

		$parameters['sort_by']['values'] = array_diff_key($parameters['sort_by']['values'], array_fill_keys(
			array('id', 'listing_type', 'zoning_type', 'purchase_type', 'mls_id', 'aid', 'aname', 'aphone', 'alicense',
				'oid', 'oname', 'ophone', 'acoid', 'aconame', 'acophone', 'acolicense', 'ocoid', 'oconame', 'ocophone'), null));

		return $parameters;
	}
}
